[project]
name = "comfyui-3d-pack-lite"
description = "Port of parts of ComfyUI 3D pack to OSX"
version = "0.1.3"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/andygill/ComfyUI-3D-Pack-Lite"

